-- Step 2: accounts and cloud storage for subscriptions.
--
-- Every table has row-level security: a signed-in user can only ever read or
-- change their own rows. Plan fields (is_pro, pro_preview) are written by the
-- server only, never by the app directly.

create function public.set_updated_at() returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Profiles: one per user, created automatically on sign-up ------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  currency text not null default 'EUR' check (currency in ('EUR', 'USD', 'GBP')),
  -- Paid Pro. Set by the Stripe webhook (step 4).
  is_pro boolean not null default false,
  -- Free preview of Pro while payments aren't live. Set by /api/pro-preview.
  pro_preview boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;

create policy "Users read their own profile" on public.profiles
  for select to authenticated using (id = (select auth.uid()));

create policy "Users update their own profile" on public.profiles
  for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

-- Users may change their settings, never their plan.
revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update (currency) on public.profiles to authenticated;

create function public.handle_new_user() returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- Subscriptions ---------------------------------------------------------------

create table public.subscriptions (
  -- Generated by the app, so the same row can be created offline and synced later.
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 1 and 80),
  price numeric(12, 2) not null check (price between 0 and 1000000),
  price_after_trial numeric(12, 2) check (price_after_trial between 0 and 1000000),
  cycle text not null check (cycle in ('week', 'month', 'quarter', 'year')),
  next_charge date not null check (next_charge between '2000-01-01' and '2100-12-31'),
  billing_day smallint not null check (billing_day between 1 and 31),
  category text not null check (
    category in ('Streaming', 'Music', 'Gaming', 'Software', 'Fitness', 'Cloud storage', 'News', 'Other')
  ),
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  used boolean not null default true,
  trial boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index subscriptions_user_id_idx on public.subscriptions (user_id);

create trigger subscriptions_updated_at before update on public.subscriptions
  for each row execute function public.set_updated_at();

alter table public.subscriptions enable row level security;

create policy "Users manage their own subscriptions" on public.subscriptions
  for all to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

revoke all on public.subscriptions from anon;
grant select, insert, update, delete on public.subscriptions to authenticated;

-- The Free plan covers 5 subscriptions. Checked here as well as in the app, so
-- it can't be bypassed by calling the API directly.
create function public.enforce_free_limit() returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  has_pro boolean;
  owned integer;
begin
  -- An upsert of an existing row is an edit, not a new subscription.
  if exists (select 1 from public.subscriptions s where s.id = new.id) then
    return new;
  end if;

  select p.is_pro or p.pro_preview into has_pro from public.profiles p where p.id = new.user_id;
  if coalesce(has_pro, false) then
    return new;
  end if;

  select count(*) into owned from public.subscriptions s where s.user_id = new.user_id;
  if owned >= 5 then
    raise exception 'The Free plan covers 5 subscriptions' using errcode = 'P0001', hint = 'free_limit';
  end if;
  return new;
end;
$$;

create trigger subscriptions_free_limit before insert on public.subscriptions
  for each row execute function public.enforce_free_limit();
